name: Build and Release

on:
  push:
    branches:
      - main
      - development
      - rc-v*
      - release/*
      - hotfix/*
  pull_request:
    types: [ready_for_review, opened, reopened, auto_merge_enabled]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - targetPlatform: linux
            os: ubuntu-latest
          # - targetPlatform: macos
          #   os: ubuntu-latest
          - targetPlatform: windows
            os: windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install
        shell: bash
        run: yarn

      - name: Setup OS variables
        run: bash scripts/configure-artifact.sh ${{ matrix.targetPlatform }}

      - name: Copy config.json from the last release
        shell: bash
        run: |
          mkdir build && yarn download-config

      - name: Copy builder config
        shell: bash
        run: |
          if [[ "${{ startsWith(github.event.ref, 'refs/tags/') }}" ]]
          then
            mv electron-builder.main.yml electron-builder.yml
          else
            mv electron-builder.internal.yml electron-builder.yml
          fi

      - name: pack
        if: ${{ !startsWith(github.event.inputs.from_branch, 'release/') }}
        shell: bash
        run: |
          yarn run pack:${{ matrix.targetPlatform }}

      - name: release
        if: ${{ startsWith(github.event.inputs.from_branch, 'release/') }} || startsWith(github.event.ref, 'refs/tags/')
        shell: bash
        run: |
          yarn run release:${{ matrix.targetPlatform }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: actions/upload-artifact@v3
        with:
          path: dist
          name: Dist-${{ matrix.targetPlatform }}
          retention-days: 3
          if-no-files-found: error
