name: Release

on:
  push:
    branches:
      - rc-v*
      - release/*
    tags: ["*"]

concurrency:
  group: release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - targetPlatform: linux
            os: ubuntu-latest
          # - targetPlatform: macos
          #   os: ubuntu-latest
          - targetPlatform: windows
            os: windows-latest
    runs-on: ${{ matrix.os }}
    environment:
      name: ${{ startsWith(github.event.ref, 'refs/tags/') && 'main' || 'internal' }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install
        shell: bash
        run: yarn

      - name: Setup OS variables
        run: bash scripts/configure-artifact.sh ${{ matrix.targetPlatform }}

      - name: Copy config.json from the last release
        shell: bash
        run: |
          mkdir build && yarn download-config

      - name: Copy builder config
        shell: bash
        run: |
          if [[ "${{ startsWith(github.event.ref, 'refs/tags/') }}" == true ]]
          then
            mv electron-builder.main.yml electron-builder.yml
          else
            mv electron-builder.internal.yml electron-builder.yml
            timestamp=$(date +%s)
            jq --arg version "0.0.$timestamp" '.version = $version' package.json > tmp.$$.json && mv tmp.$$.json package.json
            yarn
          fi

      - name: release
        shell: bash
        run: |
          yarn run release:${{ matrix.targetPlatform }}
        env:
          OS: ${{ matrix.targetPlatform }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ESIGNER_CREDENTIAL_ID: ${{ secrets.ESIGNER_CREDENTIAL_ID }}
          ESIGNER_USERNAME: ${{ secrets.ESIGNER_USERNAME }}
          ESIGNER_PASSWORD: ${{ secrets.ESIGNER_PASSWORD }}
          ESIGNER_TOTP_SECRET: ${{ secrets.ESIGNER_TOTP_SECRET }}

      - uses: actions/upload-artifact@v3
        with:
          path: dist
          name: Dist-${{ matrix.targetPlatform }}
          retention-days: 3
          if-no-files-found: error
