name: Styles

on:
  push:
    branches: ["*"]

jobs:
  styles:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install
        shell: bash
        run: yarn

      - name: Check Formatting
        run: yarn prettier --check "src/**/*.{ts,tsx,json}"

      - run: yarn codegen

      - name: Type Check
        run: yarn tsc --noEmit

      - name: ESLint Check
        run: yarn eslint ./src --quiet

  update-translations:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install
        shell: bash
        run: yarn

      - name: Update Translations
        run: yarn update-translations
        env:
          TRANSIFEX_SECRET: ${{ secrets.TRANSIFEX_SECRET }}
          TRANSIFEX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
